version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

linters:
  default: standard
  enable:
    - errcheck
    - staticcheck
    - govet
    - gocritic
    - revive
    - unused
    - gosec
    - depguard
    - bodyclose
    - asciicheck
    - cyclop
    - dupl
    - ineffassign
    - unparam
    - errorlint
    - errname
    - forbidigo
    - contextcheck
    - containedctx
  disable:
    - gocyclo
    - lll
  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - dupl
          - gosec
      - path: proto/
        linters:
          - revive
          - dupl
  settings:
    gosec:
      config:
        global:
          audit: true
        severity: "medium"
        confidence: "medium"
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: "io/ioutil is deprecated; use os/io"
    revive:
      severity: warning
    forbidigo:
      exclude-godoc-examples: true
      analyze-types: true
      forbid:
        - pattern: '^time\.Sleep$'
          msg: "avoid time.Sleep in production; use timers/context"
        - pattern: '^http\.DefaultClient$'
          msg: "do not use http.DefaultClient; create *http.Client with timeouts"

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/Eastwesser/event-horizon/)
      no-inline-comments: false
