FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY services services/
RUN cd services/inventory && go mod download && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o inventory-service ./cmd/main.go

FROM scratch
COPY --from=builder /app/services/inventory/inventory-service /inventory-service
EXPOSE 50059
CMD ["/inventory-service"]
