FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY services services/
RUN cd services/shop && go mod download && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o shop-service ./cmd/main.go

FROM scratch
COPY --from=builder /app/services/shop/shop-service /shop-service
EXPOSE 50055
CMD ["/shop-service"]
