FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY services services/
RUN cd services/billing && go mod download && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o billing-service ./cmd/main.go

FROM scratch
COPY --from=builder /app/services/billing/billing-service /billing-service
EXPOSE 50053
CMD ["/billing-service"]
