FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY services services/
RUN cd services/auth && go mod download && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o auth-service ./cmd/main.go

FROM scratch
COPY --from=builder /app/services/auth/auth-service /auth-service
EXPOSE 50051
CMD ["/auth-service"]
