// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Валюты
type CurrencyType int32

const (
	CurrencyType_CURRENCY_UNSPECIFIED CurrencyType = 0
	CurrencyType_LAMPS                CurrencyType = 1 // за активность
	CurrencyType_TICKETS              CurrencyType = 2 // пассивный доход с этажей
)

// Enum value maps for CurrencyType.
var (
	CurrencyType_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "LAMPS",
		2: "TICKETS",
	}
	CurrencyType_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"LAMPS":                1,
		"TICKETS":              2,
	}
)

func (x CurrencyType) Enum() *CurrencyType {
	p := new(CurrencyType)
	*p = x
	return p
}

func (x CurrencyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrencyType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_billing_proto_enumTypes[0].Descriptor()
}

func (CurrencyType) Type() protoreflect.EnumType {
	return &file_proto_billing_proto_enumTypes[0]
}

func (x CurrencyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrencyType.Descriptor instead.
func (CurrencyType) EnumDescriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{0}
}

// Запрос баланса
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,2,opt,name=currency,proto3,enum=billing.CurrencyType" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceRequest) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_UNSPECIFIED
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,2,opt,name=currency,proto3,enum=billing.CurrencyType" json:"currency,omitempty"`
	Balance       int32                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceResponse) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_UNSPECIFIED
}

func (x *GetBalanceResponse) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Все балансы
type GetAllBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBalancesRequest) Reset() {
	*x = GetAllBalancesRequest{}
	mi := &file_proto_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBalancesRequest) ProtoMessage() {}

func (x *GetAllBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetAllBalancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllBalancesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balances      []*BalanceEntry        `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBalancesResponse) Reset() {
	*x = GetAllBalancesResponse{}
	mi := &file_proto_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBalancesResponse) ProtoMessage() {}

func (x *GetAllBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetAllBalancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllBalancesResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllBalancesResponse) GetBalances() []*BalanceEntry {
	if x != nil {
		return x.Balances
	}
	return nil
}

type BalanceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      CurrencyType           `protobuf:"varint,1,opt,name=currency,proto3,enum=billing.CurrencyType" json:"currency,omitempty"`
	Balance       int32                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceEntry) Reset() {
	*x = BalanceEntry{}
	mi := &file_proto_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceEntry) ProtoMessage() {}

func (x *BalanceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceEntry.ProtoReflect.Descriptor instead.
func (*BalanceEntry) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceEntry) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_UNSPECIFIED
}

func (x *BalanceEntry) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BalanceEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Начисление валюты
type AddCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,2,opt,name=currency,proto3,enum=billing.CurrencyType" json:"currency,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                              // "daily_play", "new_record", "level_up", "purchase"
	ReferenceId   string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // idempotency key (например, "score.event.uuid")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCurrencyRequest) Reset() {
	*x = AddCurrencyRequest{}
	mi := &file_proto_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCurrencyRequest) ProtoMessage() {}

func (x *AddCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCurrencyRequest.ProtoReflect.Descriptor instead.
func (*AddCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{5}
}

func (x *AddCurrencyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCurrencyRequest) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_UNSPECIFIED
}

func (x *AddCurrencyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddCurrencyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AddCurrencyRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type AddCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCurrencyResponse) Reset() {
	*x = AddCurrencyResponse{}
	mi := &file_proto_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCurrencyResponse) ProtoMessage() {}

func (x *AddCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCurrencyResponse.ProtoReflect.Descriptor instead.
func (*AddCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{6}
}

func (x *AddCurrencyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddCurrencyResponse) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *AddCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Списание валюты
type SpendCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,2,opt,name=currency,proto3,enum=billing.CurrencyType" json:"currency,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                              // "hint", "reroll", "continue"
	ReferenceId   string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // idempotency key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendCurrencyRequest) Reset() {
	*x = SpendCurrencyRequest{}
	mi := &file_proto_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendCurrencyRequest) ProtoMessage() {}

func (x *SpendCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendCurrencyRequest.ProtoReflect.Descriptor instead.
func (*SpendCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{7}
}

func (x *SpendCurrencyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SpendCurrencyRequest) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_UNSPECIFIED
}

func (x *SpendCurrencyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SpendCurrencyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SpendCurrencyRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type SpendCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendCurrencyResponse) Reset() {
	*x = SpendCurrencyResponse{}
	mi := &file_proto_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendCurrencyResponse) ProtoMessage() {}

func (x *SpendCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendCurrencyResponse.ProtoReflect.Descriptor instead.
func (*SpendCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{8}
}

func (x *SpendCurrencyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SpendCurrencyResponse) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *SpendCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// История транзакций
type GetTransactionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,2,opt,name=currency,proto3,enum=billing.CurrencyType" json:"currency,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // макс 100
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_proto_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransactionHistoryRequest) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_UNSPECIFIED
}

func (x *GetTransactionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryResponse) Reset() {
	*x = GetTransactionHistoryResponse{}
	mi := &file_proto_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryResponse) ProtoMessage() {}

func (x *GetTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{10}
}

func (x *GetTransactionHistoryResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,3,opt,name=currency,proto3,enum=billing.CurrencyType" json:"currency,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter  int32                  `protobuf:"varint,5,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,7,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{11}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_UNSPECIFIED
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetBalanceAfter() int32 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *Transaction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Transaction) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Transaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_billing_proto protoreflect.FileDescriptor

const file_proto_billing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/billing.proto\x12\abilling\"_\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x15.billing.CurrencyTypeR\bcurrency\"\x99\x01\n" +
	"\x12GetBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x15.billing.CurrencyTypeR\bcurrency\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x05R\abalance\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"0\n" +
	"\x15GetAllBalancesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"d\n" +
	"\x16GetAllBalancesResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\bbalances\x18\x02 \x03(\v2\x15.billing.BalanceEntryR\bbalances\"z\n" +
	"\fBalanceEntry\x121\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x15.billing.CurrencyTypeR\bcurrency\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x05R\abalance\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"\xb3\x01\n" +
	"\x12AddCurrencyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x15.billing.CurrencyTypeR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\"j\n" +
	"\x13AddCurrencyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb5\x01\n" +
	"\x14SpendCurrencyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x15.billing.CurrencyTypeR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\"l\n" +
	"\x15SpendCurrencyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x98\x01\n" +
	"\x1cGetTransactionHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x15.billing.CurrencyTypeR\bcurrency\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"o\n" +
	"\x1dGetTransactionHistoryResponse\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.billing.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x80\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x121\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x15.billing.CurrencyTypeR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12#\n" +
	"\rbalance_after\x18\x05 \x01(\x05R\fbalanceAfter\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12!\n" +
	"\freference_id\x18\a \x01(\tR\vreferenceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt*@\n" +
	"\fCurrencyType\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LAMPS\x10\x01\x12\v\n" +
	"\aTICKETS\x10\x022\xac\x03\n" +
	"\x0eBillingService\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.billing.GetBalanceRequest\x1a\x1b.billing.GetBalanceResponse\x12Q\n" +
	"\x0eGetAllBalances\x12\x1e.billing.GetAllBalancesRequest\x1a\x1f.billing.GetAllBalancesResponse\x12H\n" +
	"\vAddCurrency\x12\x1b.billing.AddCurrencyRequest\x1a\x1c.billing.AddCurrencyResponse\x12N\n" +
	"\rSpendCurrency\x12\x1d.billing.SpendCurrencyRequest\x1a\x1e.billing.SpendCurrencyResponse\x12f\n" +
	"\x15GetTransactionHistory\x12%.billing.GetTransactionHistoryRequest\x1a&.billing.GetTransactionHistoryResponseB.Z,event_horizon/services/billing/proto;billingb\x06proto3"

var (
	file_proto_billing_proto_rawDescOnce sync.Once
	file_proto_billing_proto_rawDescData []byte
)

func file_proto_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)))
	})
	return file_proto_billing_proto_rawDescData
}

var file_proto_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_billing_proto_goTypes = []any{
	(CurrencyType)(0),                     // 0: billing.CurrencyType
	(*GetBalanceRequest)(nil),             // 1: billing.GetBalanceRequest
	(*GetBalanceResponse)(nil),            // 2: billing.GetBalanceResponse
	(*GetAllBalancesRequest)(nil),         // 3: billing.GetAllBalancesRequest
	(*GetAllBalancesResponse)(nil),        // 4: billing.GetAllBalancesResponse
	(*BalanceEntry)(nil),                  // 5: billing.BalanceEntry
	(*AddCurrencyRequest)(nil),            // 6: billing.AddCurrencyRequest
	(*AddCurrencyResponse)(nil),           // 7: billing.AddCurrencyResponse
	(*SpendCurrencyRequest)(nil),          // 8: billing.SpendCurrencyRequest
	(*SpendCurrencyResponse)(nil),         // 9: billing.SpendCurrencyResponse
	(*GetTransactionHistoryRequest)(nil),  // 10: billing.GetTransactionHistoryRequest
	(*GetTransactionHistoryResponse)(nil), // 11: billing.GetTransactionHistoryResponse
	(*Transaction)(nil),                   // 12: billing.Transaction
}
var file_proto_billing_proto_depIdxs = []int32{
	0,  // 0: billing.GetBalanceRequest.currency:type_name -> billing.CurrencyType
	0,  // 1: billing.GetBalanceResponse.currency:type_name -> billing.CurrencyType
	5,  // 2: billing.GetAllBalancesResponse.balances:type_name -> billing.BalanceEntry
	0,  // 3: billing.BalanceEntry.currency:type_name -> billing.CurrencyType
	0,  // 4: billing.AddCurrencyRequest.currency:type_name -> billing.CurrencyType
	0,  // 5: billing.SpendCurrencyRequest.currency:type_name -> billing.CurrencyType
	0,  // 6: billing.GetTransactionHistoryRequest.currency:type_name -> billing.CurrencyType
	12, // 7: billing.GetTransactionHistoryResponse.transactions:type_name -> billing.Transaction
	0,  // 8: billing.Transaction.currency:type_name -> billing.CurrencyType
	1,  // 9: billing.BillingService.GetBalance:input_type -> billing.GetBalanceRequest
	3,  // 10: billing.BillingService.GetAllBalances:input_type -> billing.GetAllBalancesRequest
	6,  // 11: billing.BillingService.AddCurrency:input_type -> billing.AddCurrencyRequest
	8,  // 12: billing.BillingService.SpendCurrency:input_type -> billing.SpendCurrencyRequest
	10, // 13: billing.BillingService.GetTransactionHistory:input_type -> billing.GetTransactionHistoryRequest
	2,  // 14: billing.BillingService.GetBalance:output_type -> billing.GetBalanceResponse
	4,  // 15: billing.BillingService.GetAllBalances:output_type -> billing.GetAllBalancesResponse
	7,  // 16: billing.BillingService.AddCurrency:output_type -> billing.AddCurrencyResponse
	9,  // 17: billing.BillingService.SpendCurrency:output_type -> billing.SpendCurrencyResponse
	11, // 18: billing.BillingService.GetTransactionHistory:output_type -> billing.GetTransactionHistoryResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_billing_proto_init() }
func file_proto_billing_proto_init() {
	if File_proto_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_proto_depIdxs,
		EnumInfos:         file_proto_billing_proto_enumTypes,
		MessageInfos:      file_proto_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_proto = out.File
	file_proto_billing_proto_goTypes = nil
	file_proto_billing_proto_depIdxs = nil
}
