// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // "hexagon" или "flappy"
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                // уровень сложности (1-5)
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                // добавить счет
	UserEmail     string                 `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Nickname      string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Seed          string                 `protobuf:"bytes,7,opt,name=seed,proto3" json:"seed,omitempty"`                                          // начальное состояние (для валидации)
	Moves         []*Move                `protobuf:"bytes,8,rep,name=moves,proto3" json:"moves,omitempty"`                                        // все ходы игрока
	ClientVersion int32                  `protobuf:"varint,10,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // для отладки (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitScoreRequest) Reset() {
	*x = SubmitScoreRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreRequest) ProtoMessage() {}

func (x *SubmitScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreRequest.ProtoReflect.Descriptor instead.
func (*SubmitScoreRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitScoreRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SubmitScoreRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SubmitScoreRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitScoreRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SubmitScoreRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SubmitScoreRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *SubmitScoreRequest) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *SubmitScoreRequest) GetClientVersion() int32 {
	if x != nil {
		return x.ClientVersion
	}
	return 0
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromX         int32                  `protobuf:"varint,1,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"`
	FromY         int32                  `protobuf:"varint,2,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	ToX           int32                  `protobuf:"varint,3,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           int32                  `protobuf:"varint,4,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	Timestamp     int32                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ms от начала игры
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetFromX() int32 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *Move) GetFromY() int32 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *Move) GetToX() int32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *Move) GetToY() int32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

func (x *Move) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SubmitScoreResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewHighscore int32                  `protobuf:"varint,2,opt,name=new_highscore,json=newHighscore,proto3" json:"new_highscore,omitempty"` // новый рекорд игрока (если побит)
	Rank         int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`                                     // место в мировом топе
	Message      string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Награды
	LampsEarned   int32 `protobuf:"varint,10,opt,name=lamps_earned,json=lampsEarned,proto3" json:"lamps_earned,omitempty"`       // лампочки за активность
	TicketsEarned int32 `protobuf:"varint,11,opt,name=tickets_earned,json=ticketsEarned,proto3" json:"tickets_earned,omitempty"` // билетики за рекорд
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitScoreResponse) Reset() {
	*x = SubmitScoreResponse{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreResponse) ProtoMessage() {}

func (x *SubmitScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreResponse.ProtoReflect.Descriptor instead.
func (*SubmitScoreResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitScoreResponse) GetNewHighscore() int32 {
	if x != nil {
		return x.NewHighscore
	}
	return 0
}

func (x *SubmitScoreResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *SubmitScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitScoreResponse) GetLampsEarned() int32 {
	if x != nil {
		return x.LampsEarned
	}
	return 0
}

func (x *SubmitScoreResponse) GetTicketsEarned() int32 {
	if x != nil {
		return x.TicketsEarned
	}
	return 0
}

type GetGameInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameInfoRequest) Reset() {
	*x = GetGameInfoRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameInfoRequest) ProtoMessage() {}

func (x *GetGameInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGameInfoRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameInfoRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Levels        []*LevelInfo           `protobuf:"bytes,4,rep,name=levels,proto3" json:"levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameInfoResponse) Reset() {
	*x = GetGameInfoResponse{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameInfoResponse) ProtoMessage() {}

func (x *GetGameInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameInfoResponse.ProtoReflect.Descriptor instead.
func (*GetGameInfoResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameInfoResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGameInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetGameInfoResponse) GetLevels() []*LevelInfo {
	if x != nil {
		return x.Levels
	}
	return nil
}

type LevelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	TargetScore   int32                  `protobuf:"varint,2,opt,name=target_score,json=targetScore,proto3" json:"target_score,omitempty"` // сколько очков нужно для прохода
	RewardLamps   int32                  `protobuf:"varint,3,opt,name=reward_lamps,json=rewardLamps,proto3" json:"reward_lamps,omitempty"`
	RewardTickets int32                  `protobuf:"varint,4,opt,name=reward_tickets,json=rewardTickets,proto3" json:"reward_tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelInfo) Reset() {
	*x = LevelInfo{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelInfo) ProtoMessage() {}

func (x *LevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelInfo.ProtoReflect.Descriptor instead.
func (*LevelInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *LevelInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LevelInfo) GetTargetScore() int32 {
	if x != nil {
		return x.TargetScore
	}
	return 0
}

func (x *LevelInfo) GetRewardLamps() int32 {
	if x != nil {
		return x.RewardLamps
	}
	return 0
}

func (x *LevelInfo) GetRewardTickets() int32 {
	if x != nil {
		return x.RewardTickets
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"\x8a\x02\n" +
	"\x12SubmitScoreRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x12\n" +
	"\x04seed\x18\a \x01(\tR\x04seed\x12 \n" +
	"\x05moves\x18\b \x03(\v2\n" +
	".game.MoveR\x05moves\x12%\n" +
	"\x0eclient_version\x18\n" +
	" \x01(\x05R\rclientVersion\"x\n" +
	"\x04Move\x12\x15\n" +
	"\x06from_x\x18\x01 \x01(\x05R\x05fromX\x12\x15\n" +
	"\x06from_y\x18\x02 \x01(\x05R\x05fromY\x12\x11\n" +
	"\x04to_x\x18\x03 \x01(\x05R\x03toX\x12\x11\n" +
	"\x04to_y\x18\x04 \x01(\x05R\x03toY\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x05R\ttimestamp\"\xcc\x01\n" +
	"\x13SubmitScoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rnew_highscore\x18\x02 \x01(\x05R\fnewHighscore\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\flamps_earned\x18\n" +
	" \x01(\x05R\vlampsEarned\x12%\n" +
	"\x0etickets_earned\x18\v \x01(\x05R\rticketsEarned\"-\n" +
	"\x12GetGameInfoRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"\x8d\x01\n" +
	"\x13GetGameInfoResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x06levels\x18\x04 \x03(\v2\x0f.game.LevelInfoR\x06levels\"\x8e\x01\n" +
	"\tLevelInfo\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12!\n" +
	"\ftarget_score\x18\x02 \x01(\x05R\vtargetScore\x12!\n" +
	"\freward_lamps\x18\x03 \x01(\x05R\vrewardLamps\x12%\n" +
	"\x0ereward_tickets\x18\x04 \x01(\x05R\rrewardTickets2\x95\x01\n" +
	"\vGameService\x12B\n" +
	"\vSubmitScore\x12\x18.game.SubmitScoreRequest\x1a\x19.game.SubmitScoreResponse\x12B\n" +
	"\vGetGameInfo\x12\x18.game.GetGameInfoRequest\x1a\x19.game.GetGameInfoResponseB(Z&github.com/Eastwesser/event-horizon/services/game/proto;gameb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_game_proto_goTypes = []any{
	(*SubmitScoreRequest)(nil),  // 0: game.SubmitScoreRequest
	(*Move)(nil),                // 1: game.Move
	(*SubmitScoreResponse)(nil), // 2: game.SubmitScoreResponse
	(*GetGameInfoRequest)(nil),  // 3: game.GetGameInfoRequest
	(*GetGameInfoResponse)(nil), // 4: game.GetGameInfoResponse
	(*LevelInfo)(nil),           // 5: game.LevelInfo
}
var file_game_proto_depIdxs = []int32{
	1, // 0: game.SubmitScoreRequest.moves:type_name -> game.Move
	5, // 1: game.GetGameInfoResponse.levels:type_name -> game.LevelInfo
	0, // 2: game.GameService.SubmitScore:input_type -> game.SubmitScoreRequest
	3, // 3: game.GameService.GetGameInfo:input_type -> game.GetGameInfoRequest
	2, // 4: game.GameService.SubmitScore:output_type -> game.SubmitScoreResponse
	4, // 5: game.GameService.GetGameInfo:output_type -> game.GetGameInfoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
