// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/leaderboard.proto

package leaderboard

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopScoresRequest) Reset() {
	*x = GetTopScoresRequest{}
	mi := &file_proto_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopScoresRequest) ProtoMessage() {}

func (x *GetTopScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopScoresRequest.ProtoReflect.Descriptor instead.
func (*GetTopScoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopScoresRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetTopScoresRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ScoreEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopScoresResponse) Reset() {
	*x = GetTopScoresResponse{}
	mi := &file_proto_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopScoresResponse) ProtoMessage() {}

func (x *GetTopScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopScoresResponse.ProtoReflect.Descriptor instead.
func (*GetTopScoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopScoresResponse) GetEntries() []*ScoreEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetPlayerRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRankRequest) Reset() {
	*x = GetPlayerRankRequest{}
	mi := &file_proto_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRankRequest) ProtoMessage() {}

func (x *GetPlayerRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRankRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRankRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerRankRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetPlayerRankRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPlayerRankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRankResponse) Reset() {
	*x = GetPlayerRankResponse{}
	mi := &file_proto_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRankResponse) ProtoMessage() {}

func (x *GetPlayerRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRankResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerRankResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerRankResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetPlayerRankResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UpdateScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreRequest) Reset() {
	*x = UpdateScoreRequest{}
	mi := &file_proto_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreRequest) ProtoMessage() {}

func (x *UpdateScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateScoreRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UpdateScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateScoreRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UpdateScoreRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateScoreRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UpdateScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewRank       int32                  `protobuf:"varint,2,opt,name=new_rank,json=newRank,proto3" json:"new_rank,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreResponse) Reset() {
	*x = UpdateScoreResponse{}
	mi := &file_proto_leaderboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreResponse) ProtoMessage() {}

func (x *UpdateScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateScoreResponse) GetNewRank() int32 {
	if x != nil {
		return x.NewRank
	}
	return 0
}

func (x *UpdateScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreEntry) Reset() {
	*x = ScoreEntry{}
	mi := &file_proto_leaderboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEntry) ProtoMessage() {}

func (x *ScoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leaderboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEntry.ProtoReflect.Descriptor instead.
func (*ScoreEntry) Descriptor() ([]byte, []int) {
	return file_proto_leaderboard_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ScoreEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScoreEntry) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *ScoreEntry) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ScoreEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_proto_leaderboard_proto protoreflect.FileDescriptor

const file_proto_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x17proto/leaderboard.proto\x12\vleaderboard\x1a\x17validate/validate.proto\"Z\n" +
	"\x13GetTopScoresRequest\x12\"\n" +
	"\agame_id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\x06gameId\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\x05limit\"I\n" +
	"\x14GetTopScoresResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.leaderboard.ScoreEntryR\aentries\"^\n" +
	"\x14GetPlayerRankRequest\x12\"\n" +
	"\agame_id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\x06gameId\x12\"\n" +
	"\auser_id\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x06userId\"A\n" +
	"\x15GetPlayerRankResponse\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"\xcd\x01\n" +
	"\x12UpdateScoreRequest\x12\"\n" +
	"\agame_id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\x06gameId\x12\"\n" +
	"\auser_id\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x06userId\x12'\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xfe\x01R\tuserEmail\x12#\n" +
	"\bnickname\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x18@R\bnickname\x12!\n" +
	"\x05score\x18\x05 \x01(\x05B\v\xfaB\b\x1a\x06\x18\xa0\x8d\x06(\x00R\x05score\"d\n" +
	"\x13UpdateScoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bnew_rank\x18\x02 \x01(\x05R\anewRank\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa9\x01\n" +
	"\n" +
	"ScoreEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt2\x93\x02\n" +
	"\x12LeaderboardService\x12S\n" +
	"\fGetTopScores\x12 .leaderboard.GetTopScoresRequest\x1a!.leaderboard.GetTopScoresResponse\x12V\n" +
	"\rGetPlayerRank\x12!.leaderboard.GetPlayerRankRequest\x1a\".leaderboard.GetPlayerRankResponse\x12P\n" +
	"\vUpdateScore\x12\x1f.leaderboard.UpdateScoreRequest\x1a .leaderboard.UpdateScoreResponseB6Z4event_horizon/services/leaderboard/proto;leaderboardb\x06proto3"

var (
	file_proto_leaderboard_proto_rawDescOnce sync.Once
	file_proto_leaderboard_proto_rawDescData []byte
)

func file_proto_leaderboard_proto_rawDescGZIP() []byte {
	file_proto_leaderboard_proto_rawDescOnce.Do(func() {
		file_proto_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_leaderboard_proto_rawDesc), len(file_proto_leaderboard_proto_rawDesc)))
	})
	return file_proto_leaderboard_proto_rawDescData
}

var file_proto_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_leaderboard_proto_goTypes = []any{
	(*GetTopScoresRequest)(nil),   // 0: leaderboard.GetTopScoresRequest
	(*GetTopScoresResponse)(nil),  // 1: leaderboard.GetTopScoresResponse
	(*GetPlayerRankRequest)(nil),  // 2: leaderboard.GetPlayerRankRequest
	(*GetPlayerRankResponse)(nil), // 3: leaderboard.GetPlayerRankResponse
	(*UpdateScoreRequest)(nil),    // 4: leaderboard.UpdateScoreRequest
	(*UpdateScoreResponse)(nil),   // 5: leaderboard.UpdateScoreResponse
	(*ScoreEntry)(nil),            // 6: leaderboard.ScoreEntry
}
var file_proto_leaderboard_proto_depIdxs = []int32{
	6, // 0: leaderboard.GetTopScoresResponse.entries:type_name -> leaderboard.ScoreEntry
	0, // 1: leaderboard.LeaderboardService.GetTopScores:input_type -> leaderboard.GetTopScoresRequest
	2, // 2: leaderboard.LeaderboardService.GetPlayerRank:input_type -> leaderboard.GetPlayerRankRequest
	4, // 3: leaderboard.LeaderboardService.UpdateScore:input_type -> leaderboard.UpdateScoreRequest
	1, // 4: leaderboard.LeaderboardService.GetTopScores:output_type -> leaderboard.GetTopScoresResponse
	3, // 5: leaderboard.LeaderboardService.GetPlayerRank:output_type -> leaderboard.GetPlayerRankResponse
	5, // 6: leaderboard.LeaderboardService.UpdateScore:output_type -> leaderboard.UpdateScoreResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_leaderboard_proto_init() }
func file_proto_leaderboard_proto_init() {
	if File_proto_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_leaderboard_proto_rawDesc), len(file_proto_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leaderboard_proto_goTypes,
		DependencyIndexes: file_proto_leaderboard_proto_depIdxs,
		MessageInfos:      file_proto_leaderboard_proto_msgTypes,
	}.Build()
	File_proto_leaderboard_proto = out.File
	file_proto_leaderboard_proto_goTypes = nil
	file_proto_leaderboard_proto_depIdxs = nil
}
