// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: proto/leaderboard.proto

package leaderboard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderboardService_GetTopScores_FullMethodName  = "/leaderboard.LeaderboardService/GetTopScores"
	LeaderboardService_GetPlayerRank_FullMethodName = "/leaderboard.LeaderboardService/GetPlayerRank"
	LeaderboardService_UpdateScore_FullMethodName   = "/leaderboard.LeaderboardService/UpdateScore"
)

// LeaderboardServiceClient is the client API for LeaderboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderboardServiceClient interface {
	// Получить топ-N игроков для конкретной игры
	GetTopScores(ctx context.Context, in *GetTopScoresRequest, opts ...grpc.CallOption) (*GetTopScoresResponse, error)
	// Получить место конкретного игрока в топе
	GetPlayerRank(ctx context.Context, in *GetPlayerRankRequest, opts ...grpc.CallOption) (*GetPlayerRankResponse, error)
	// Обновить рекорд (будет вызываться через NATS, но gRPC тоже держим)
	UpdateScore(ctx context.Context, in *UpdateScoreRequest, opts ...grpc.CallOption) (*UpdateScoreResponse, error)
}

type leaderboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderboardServiceClient(cc grpc.ClientConnInterface) LeaderboardServiceClient {
	return &leaderboardServiceClient{cc}
}

func (c *leaderboardServiceClient) GetTopScores(ctx context.Context, in *GetTopScoresRequest, opts ...grpc.CallOption) (*GetTopScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopScoresResponse)
	err := c.cc.Invoke(ctx, LeaderboardService_GetTopScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardServiceClient) GetPlayerRank(ctx context.Context, in *GetPlayerRankRequest, opts ...grpc.CallOption) (*GetPlayerRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerRankResponse)
	err := c.cc.Invoke(ctx, LeaderboardService_GetPlayerRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardServiceClient) UpdateScore(ctx context.Context, in *UpdateScoreRequest, opts ...grpc.CallOption) (*UpdateScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardService_UpdateScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderboardServiceServer is the server API for LeaderboardService service.
// All implementations must embed UnimplementedLeaderboardServiceServer
// for forward compatibility.
type LeaderboardServiceServer interface {
	// Получить топ-N игроков для конкретной игры
	GetTopScores(context.Context, *GetTopScoresRequest) (*GetTopScoresResponse, error)
	// Получить место конкретного игрока в топе
	GetPlayerRank(context.Context, *GetPlayerRankRequest) (*GetPlayerRankResponse, error)
	// Обновить рекорд (будет вызываться через NATS, но gRPC тоже держим)
	UpdateScore(context.Context, *UpdateScoreRequest) (*UpdateScoreResponse, error)
	mustEmbedUnimplementedLeaderboardServiceServer()
}

// UnimplementedLeaderboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderboardServiceServer struct{}

func (UnimplementedLeaderboardServiceServer) GetTopScores(context.Context, *GetTopScoresRequest) (*GetTopScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopScores not implemented")
}
func (UnimplementedLeaderboardServiceServer) GetPlayerRank(context.Context, *GetPlayerRankRequest) (*GetPlayerRankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerRank not implemented")
}
func (UnimplementedLeaderboardServiceServer) UpdateScore(context.Context, *UpdateScoreRequest) (*UpdateScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateScore not implemented")
}
func (UnimplementedLeaderboardServiceServer) mustEmbedUnimplementedLeaderboardServiceServer() {}
func (UnimplementedLeaderboardServiceServer) testEmbeddedByValue()                            {}

// UnsafeLeaderboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderboardServiceServer will
// result in compilation errors.
type UnsafeLeaderboardServiceServer interface {
	mustEmbedUnimplementedLeaderboardServiceServer()
}

func RegisterLeaderboardServiceServer(s grpc.ServiceRegistrar, srv LeaderboardServiceServer) {
	// If the following call panics, it indicates UnimplementedLeaderboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderboardService_ServiceDesc, srv)
}

func _LeaderboardService_GetTopScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardServiceServer).GetTopScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardService_GetTopScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardServiceServer).GetTopScores(ctx, req.(*GetTopScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardService_GetPlayerRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardServiceServer).GetPlayerRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardService_GetPlayerRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardServiceServer).GetPlayerRank(ctx, req.(*GetPlayerRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardService_UpdateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardServiceServer).UpdateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardService_UpdateScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardServiceServer).UpdateScore(ctx, req.(*UpdateScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderboardService_ServiceDesc is the grpc.ServiceDesc for LeaderboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leaderboard.LeaderboardService",
	HandlerType: (*LeaderboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopScores",
			Handler:    _LeaderboardService_GetTopScores_Handler,
		},
		{
			MethodName: "GetPlayerRank",
			Handler:    _LeaderboardService_GetPlayerRank_Handler,
		},
		{
			MethodName: "UpdateScore",
			Handler:    _LeaderboardService_UpdateScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/leaderboard.proto",
}
