// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/authors.proto

package authors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,8,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_proto_authors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_proto_authors_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Author) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Author) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Author) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Author) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Author) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type UpsertProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProfileRequest) Reset() {
	*x = UpsertProfileRequest{}
	mi := &file_proto_authors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProfileRequest) ProtoMessage() {}

func (x *UpsertProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProfileRequest.ProtoReflect.Descriptor instead.
func (*UpsertProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_authors_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpsertProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpsertProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpsertProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProfileResponse) Reset() {
	*x = UpsertProfileResponse{}
	mi := &file_proto_authors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProfileResponse) ProtoMessage() {}

func (x *UpsertProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProfileResponse.ProtoReflect.Descriptor instead.
func (*UpsertProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_authors_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertProfileResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_proto_authors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_authors_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_proto_authors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_authors_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListAuthorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsRequest) Reset() {
	*x = ListAuthorsRequest{}
	mi := &file_proto_authors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsRequest) ProtoMessage() {}

func (x *ListAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_authors_proto_rawDescGZIP(), []int{5}
}

func (x *ListAuthorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuthorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsResponse) Reset() {
	*x = ListAuthorsResponse{}
	mi := &file_proto_authors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsResponse) ProtoMessage() {}

func (x *ListAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_authors_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *ListAuthorsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_authors_proto protoreflect.FileDescriptor

const file_proto_authors_proto_rawDesc = "" +
	"\n" +
	"\x13proto/authors.proto\x12\aauthors\"\xed\x01\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\b \x01(\x03R\rupdatedAtUnix\"\x83\x01\n" +
	"\x14UpsertProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"@\n" +
	"\x15UpsertProfileResponse\x12'\n" +
	"\x06author\x18\x01 \x01(\v2\x0f.authors.AuthorR\x06author\"+\n" +
	"\x10GetAuthorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x11GetAuthorResponse\x12'\n" +
	"\x06author\x18\x01 \x01(\v2\x0f.authors.AuthorR\x06author\"B\n" +
	"\x12ListAuthorsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"V\n" +
	"\x13ListAuthorsResponse\x12)\n" +
	"\aauthors\x18\x01 \x03(\v2\x0f.authors.AuthorR\aauthors\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xee\x01\n" +
	"\x0eAuthorsService\x12N\n" +
	"\rUpsertProfile\x12\x1d.authors.UpsertProfileRequest\x1a\x1e.authors.UpsertProfileResponse\x12B\n" +
	"\tGetAuthor\x12\x19.authors.GetAuthorRequest\x1a\x1a.authors.GetAuthorResponse\x12H\n" +
	"\vListAuthors\x12\x1b.authors.ListAuthorsRequest\x1a\x1c.authors.ListAuthorsResponseBDZBgithub.com/Eastwesser/event-horizon/services/authors/proto;authorsb\x06proto3"

var (
	file_proto_authors_proto_rawDescOnce sync.Once
	file_proto_authors_proto_rawDescData []byte
)

func file_proto_authors_proto_rawDescGZIP() []byte {
	file_proto_authors_proto_rawDescOnce.Do(func() {
		file_proto_authors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authors_proto_rawDesc), len(file_proto_authors_proto_rawDesc)))
	})
	return file_proto_authors_proto_rawDescData
}

var file_proto_authors_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_authors_proto_goTypes = []any{
	(*Author)(nil),                // 0: authors.Author
	(*UpsertProfileRequest)(nil),  // 1: authors.UpsertProfileRequest
	(*UpsertProfileResponse)(nil), // 2: authors.UpsertProfileResponse
	(*GetAuthorRequest)(nil),      // 3: authors.GetAuthorRequest
	(*GetAuthorResponse)(nil),     // 4: authors.GetAuthorResponse
	(*ListAuthorsRequest)(nil),    // 5: authors.ListAuthorsRequest
	(*ListAuthorsResponse)(nil),   // 6: authors.ListAuthorsResponse
}
var file_proto_authors_proto_depIdxs = []int32{
	0, // 0: authors.UpsertProfileResponse.author:type_name -> authors.Author
	0, // 1: authors.GetAuthorResponse.author:type_name -> authors.Author
	0, // 2: authors.ListAuthorsResponse.authors:type_name -> authors.Author
	1, // 3: authors.AuthorsService.UpsertProfile:input_type -> authors.UpsertProfileRequest
	3, // 4: authors.AuthorsService.GetAuthor:input_type -> authors.GetAuthorRequest
	5, // 5: authors.AuthorsService.ListAuthors:input_type -> authors.ListAuthorsRequest
	2, // 6: authors.AuthorsService.UpsertProfile:output_type -> authors.UpsertProfileResponse
	4, // 7: authors.AuthorsService.GetAuthor:output_type -> authors.GetAuthorResponse
	6, // 8: authors.AuthorsService.ListAuthors:output_type -> authors.ListAuthorsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_authors_proto_init() }
func file_proto_authors_proto_init() {
	if File_proto_authors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authors_proto_rawDesc), len(file_proto_authors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authors_proto_goTypes,
		DependencyIndexes: file_proto_authors_proto_depIdxs,
		MessageInfos:      file_proto_authors_proto_msgTypes,
	}.Build()
	File_proto_authors_proto = out.File
	file_proto_authors_proto_goTypes = nil
	file_proto_authors_proto_depIdxs = nil
}
