// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: authors.proto

package authors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio            string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Active         bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAtUnix  int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix  int64                  `protobuf:"varint,8,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Portfolio      string                 `protobuf:"bytes,9,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	VerifiedAtUnix int64                  `protobuf:"varint,10,opt,name=verified_at_unix,json=verifiedAtUnix,proto3" json:"verified_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_authors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Author) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Author) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Author) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Author) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Author) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Author) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

func (x *Author) GetVerifiedAtUnix() int64 {
	if x != nil {
		return x.VerifiedAtUnix
	}
	return 0
}

type UpsertProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Portfolio     string                 `protobuf:"bytes,5,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProfileRequest) Reset() {
	*x = UpsertProfileRequest{}
	mi := &file_authors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProfileRequest) ProtoMessage() {}

func (x *UpsertProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProfileRequest.ProtoReflect.Descriptor instead.
func (*UpsertProfileRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpsertProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpsertProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpsertProfileRequest) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type UpsertProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProfileResponse) Reset() {
	*x = UpsertProfileResponse{}
	mi := &file_authors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProfileResponse) ProtoMessage() {}

func (x *UpsertProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProfileResponse.ProtoReflect.Descriptor instead.
func (*UpsertProfileResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertProfileResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_authors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_authors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListAuthorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsRequest) Reset() {
	*x = ListAuthorsRequest{}
	mi := &file_authors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsRequest) ProtoMessage() {}

func (x *ListAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{5}
}

func (x *ListAuthorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuthorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsResponse) Reset() {
	*x = ListAuthorsResponse{}
	mi := &file_authors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsResponse) ProtoMessage() {}

func (x *ListAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *ListAuthorsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AuthorApplication struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pending | approved | rejected
	DisplayName    string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Portfolio      string                 `protobuf:"bytes,5,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	Motivation     string                 `protobuf:"bytes,6,opt,name=motivation,proto3" json:"motivation,omitempty"`
	ContactEmail   string                 `protobuf:"bytes,7,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	CreatedAtUnix  int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	ReviewedAtUnix int64                  `protobuf:"varint,9,opt,name=reviewed_at_unix,json=reviewedAtUnix,proto3" json:"reviewed_at_unix,omitempty"`
	ReviewedBy     string                 `protobuf:"bytes,10,opt,name=reviewed_by,json=reviewedBy,proto3" json:"reviewed_by,omitempty"`
	ReviewerNote   string                 `protobuf:"bytes,11,opt,name=reviewer_note,json=reviewerNote,proto3" json:"reviewer_note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorApplication) Reset() {
	*x = AuthorApplication{}
	mi := &file_authors_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorApplication) ProtoMessage() {}

func (x *AuthorApplication) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorApplication.ProtoReflect.Descriptor instead.
func (*AuthorApplication) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthorApplication) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthorApplication) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorApplication) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AuthorApplication) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

func (x *AuthorApplication) GetMotivation() string {
	if x != nil {
		return x.Motivation
	}
	return ""
}

func (x *AuthorApplication) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *AuthorApplication) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *AuthorApplication) GetReviewedAtUnix() int64 {
	if x != nil {
		return x.ReviewedAtUnix
	}
	return 0
}

func (x *AuthorApplication) GetReviewedBy() string {
	if x != nil {
		return x.ReviewedBy
	}
	return ""
}

func (x *AuthorApplication) GetReviewerNote() string {
	if x != nil {
		return x.ReviewerNote
	}
	return ""
}

type SubmitApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallerRole    string                 `protobuf:"bytes,2,opt,name=caller_role,json=callerRole,proto3" json:"caller_role,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Portfolio     string                 `protobuf:"bytes,4,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	Motivation    string                 `protobuf:"bytes,5,opt,name=motivation,proto3" json:"motivation,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationRequest) Reset() {
	*x = SubmitApplicationRequest{}
	mi := &file_authors_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationRequest) ProtoMessage() {}

func (x *SubmitApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationRequest.ProtoReflect.Descriptor instead.
func (*SubmitApplicationRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitApplicationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitApplicationRequest) GetCallerRole() string {
	if x != nil {
		return x.CallerRole
	}
	return ""
}

func (x *SubmitApplicationRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SubmitApplicationRequest) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

func (x *SubmitApplicationRequest) GetMotivation() string {
	if x != nil {
		return x.Motivation
	}
	return ""
}

func (x *SubmitApplicationRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

type SubmitApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *AuthorApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationResponse) Reset() {
	*x = SubmitApplicationResponse{}
	mi := &file_authors_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationResponse) ProtoMessage() {}

func (x *SubmitApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationResponse.ProtoReflect.Descriptor instead.
func (*SubmitApplicationResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitApplicationResponse) GetApplication() *AuthorApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

type GetMyApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyApplicationRequest) Reset() {
	*x = GetMyApplicationRequest{}
	mi := &file_authors_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyApplicationRequest) ProtoMessage() {}

func (x *GetMyApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetMyApplicationRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyApplicationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMyApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *AuthorApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyApplicationResponse) Reset() {
	*x = GetMyApplicationResponse{}
	mi := &file_authors_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyApplicationResponse) ProtoMessage() {}

func (x *GetMyApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetMyApplicationResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{11}
}

func (x *GetMyApplicationResponse) GetApplication() *AuthorApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // pending|approved|rejected|"" (all)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_authors_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{12}
}

func (x *ListApplicationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListApplicationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListApplicationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*AuthorApplication   `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_authors_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{13}
}

func (x *ListApplicationsResponse) GetApplications() []*AuthorApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ApproveApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ReviewerId    string                 `protobuf:"bytes,2,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveApplicationRequest) Reset() {
	*x = ApproveApplicationRequest{}
	mi := &file_authors_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveApplicationRequest) ProtoMessage() {}

func (x *ApproveApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveApplicationRequest.ProtoReflect.Descriptor instead.
func (*ApproveApplicationRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{14}
}

func (x *ApproveApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApproveApplicationRequest) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

type ApproveApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *AuthorApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Author        *Author                `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveApplicationResponse) Reset() {
	*x = ApproveApplicationResponse{}
	mi := &file_authors_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveApplicationResponse) ProtoMessage() {}

func (x *ApproveApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveApplicationResponse.ProtoReflect.Descriptor instead.
func (*ApproveApplicationResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{15}
}

func (x *ApproveApplicationResponse) GetApplication() *AuthorApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *ApproveApplicationResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type RejectApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ReviewerId    string                 `protobuf:"bytes,2,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	ReviewerNote  string                 `protobuf:"bytes,3,opt,name=reviewer_note,json=reviewerNote,proto3" json:"reviewer_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectApplicationRequest) Reset() {
	*x = RejectApplicationRequest{}
	mi := &file_authors_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectApplicationRequest) ProtoMessage() {}

func (x *RejectApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectApplicationRequest.ProtoReflect.Descriptor instead.
func (*RejectApplicationRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{16}
}

func (x *RejectApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *RejectApplicationRequest) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *RejectApplicationRequest) GetReviewerNote() string {
	if x != nil {
		return x.ReviewerNote
	}
	return ""
}

type RejectApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *AuthorApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectApplicationResponse) Reset() {
	*x = RejectApplicationResponse{}
	mi := &file_authors_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectApplicationResponse) ProtoMessage() {}

func (x *RejectApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectApplicationResponse.ProtoReflect.Descriptor instead.
func (*RejectApplicationResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{17}
}

func (x *RejectApplicationResponse) GetApplication() *AuthorApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

type RevertApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertApplicationRequest) Reset() {
	*x = RevertApplicationRequest{}
	mi := &file_authors_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertApplicationRequest) ProtoMessage() {}

func (x *RevertApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertApplicationRequest.ProtoReflect.Descriptor instead.
func (*RevertApplicationRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{18}
}

func (x *RevertApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type RevertApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *AuthorApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertApplicationResponse) Reset() {
	*x = RevertApplicationResponse{}
	mi := &file_authors_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertApplicationResponse) ProtoMessage() {}

func (x *RevertApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertApplicationResponse.ProtoReflect.Descriptor instead.
func (*RevertApplicationResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{19}
}

func (x *RevertApplicationResponse) GetApplication() *AuthorApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_authors_proto protoreflect.FileDescriptor

const file_authors_proto_rawDesc = "" +
	"\n" +
	"\rauthors.proto\x12\aauthors\"\xb5\x02\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\b \x01(\x03R\rupdatedAtUnix\x12\x1c\n" +
	"\tportfolio\x18\t \x01(\tR\tportfolio\x12(\n" +
	"\x10verified_at_unix\x18\n" +
	" \x01(\x03R\x0everifiedAtUnix\"\xa1\x01\n" +
	"\x14UpsertProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\tportfolio\x18\x05 \x01(\tR\tportfolio\"@\n" +
	"\x15UpsertProfileResponse\x12'\n" +
	"\x06author\x18\x01 \x01(\v2\x0f.authors.AuthorR\x06author\"+\n" +
	"\x10GetAuthorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x11GetAuthorResponse\x12'\n" +
	"\x06author\x18\x01 \x01(\v2\x0f.authors.AuthorR\x06author\"B\n" +
	"\x12ListAuthorsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"V\n" +
	"\x13ListAuthorsResponse\x12)\n" +
	"\aauthors\x18\x01 \x03(\v2\x0f.authors.AuthorR\aauthors\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xf2\x02\n" +
	"\x11AuthorApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1c\n" +
	"\tportfolio\x18\x05 \x01(\tR\tportfolio\x12\x1e\n" +
	"\n" +
	"motivation\x18\x06 \x01(\tR\n" +
	"motivation\x12#\n" +
	"\rcontact_email\x18\a \x01(\tR\fcontactEmail\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\x12(\n" +
	"\x10reviewed_at_unix\x18\t \x01(\x03R\x0ereviewedAtUnix\x12\x1f\n" +
	"\vreviewed_by\x18\n" +
	" \x01(\tR\n" +
	"reviewedBy\x12#\n" +
	"\rreviewer_note\x18\v \x01(\tR\freviewerNote\"\xda\x01\n" +
	"\x18SubmitApplicationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcaller_role\x18\x02 \x01(\tR\n" +
	"callerRole\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1c\n" +
	"\tportfolio\x18\x04 \x01(\tR\tportfolio\x12\x1e\n" +
	"\n" +
	"motivation\x18\x05 \x01(\tR\n" +
	"motivation\x12#\n" +
	"\rcontact_email\x18\x06 \x01(\tR\fcontactEmail\"Y\n" +
	"\x19SubmitApplicationResponse\x12<\n" +
	"\vapplication\x18\x01 \x01(\v2\x1a.authors.AuthorApplicationR\vapplication\"2\n" +
	"\x17GetMyApplicationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"X\n" +
	"\x18GetMyApplicationResponse\x12<\n" +
	"\vapplication\x18\x01 \x01(\v2\x1a.authors.AuthorApplicationR\vapplication\"_\n" +
	"\x17ListApplicationsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"p\n" +
	"\x18ListApplicationsResponse\x12>\n" +
	"\fapplications\x18\x01 \x03(\v2\x1a.authors.AuthorApplicationR\fapplications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"c\n" +
	"\x19ApproveApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x1f\n" +
	"\vreviewer_id\x18\x02 \x01(\tR\n" +
	"reviewerId\"\x83\x01\n" +
	"\x1aApproveApplicationResponse\x12<\n" +
	"\vapplication\x18\x01 \x01(\v2\x1a.authors.AuthorApplicationR\vapplication\x12'\n" +
	"\x06author\x18\x02 \x01(\v2\x0f.authors.AuthorR\x06author\"\x87\x01\n" +
	"\x18RejectApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x1f\n" +
	"\vreviewer_id\x18\x02 \x01(\tR\n" +
	"reviewerId\x12#\n" +
	"\rreviewer_note\x18\x03 \x01(\tR\freviewerNote\"Y\n" +
	"\x19RejectApplicationResponse\x12<\n" +
	"\vapplication\x18\x01 \x01(\v2\x1a.authors.AuthorApplicationR\vapplication\"A\n" +
	"\x18RevertApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"Y\n" +
	"\x19RevertApplicationResponse\x12<\n" +
	"\vapplication\x18\x01 \x01(\v2\x1a.authors.AuthorApplicationR\vapplication2\x93\x06\n" +
	"\x0eAuthorsService\x12N\n" +
	"\rUpsertProfile\x12\x1d.authors.UpsertProfileRequest\x1a\x1e.authors.UpsertProfileResponse\x12B\n" +
	"\tGetAuthor\x12\x19.authors.GetAuthorRequest\x1a\x1a.authors.GetAuthorResponse\x12H\n" +
	"\vListAuthors\x12\x1b.authors.ListAuthorsRequest\x1a\x1c.authors.ListAuthorsResponse\x12Z\n" +
	"\x11SubmitApplication\x12!.authors.SubmitApplicationRequest\x1a\".authors.SubmitApplicationResponse\x12W\n" +
	"\x10GetMyApplication\x12 .authors.GetMyApplicationRequest\x1a!.authors.GetMyApplicationResponse\x12W\n" +
	"\x10ListApplications\x12 .authors.ListApplicationsRequest\x1a!.authors.ListApplicationsResponse\x12]\n" +
	"\x12ApproveApplication\x12\".authors.ApproveApplicationRequest\x1a#.authors.ApproveApplicationResponse\x12Z\n" +
	"\x11RejectApplication\x12!.authors.RejectApplicationRequest\x1a\".authors.RejectApplicationResponse\x12Z\n" +
	"\x11RevertApplication\x12!.authors.RevertApplicationRequest\x1a\".authors.RevertApplicationResponseBDZBgithub.com/Eastwesser/event-horizon/services/authors/proto;authorsb\x06proto3"

var (
	file_authors_proto_rawDescOnce sync.Once
	file_authors_proto_rawDescData []byte
)

func file_authors_proto_rawDescGZIP() []byte {
	file_authors_proto_rawDescOnce.Do(func() {
		file_authors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authors_proto_rawDesc), len(file_authors_proto_rawDesc)))
	})
	return file_authors_proto_rawDescData
}

var file_authors_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_authors_proto_goTypes = []any{
	(*Author)(nil),                     // 0: authors.Author
	(*UpsertProfileRequest)(nil),       // 1: authors.UpsertProfileRequest
	(*UpsertProfileResponse)(nil),      // 2: authors.UpsertProfileResponse
	(*GetAuthorRequest)(nil),           // 3: authors.GetAuthorRequest
	(*GetAuthorResponse)(nil),          // 4: authors.GetAuthorResponse
	(*ListAuthorsRequest)(nil),         // 5: authors.ListAuthorsRequest
	(*ListAuthorsResponse)(nil),        // 6: authors.ListAuthorsResponse
	(*AuthorApplication)(nil),          // 7: authors.AuthorApplication
	(*SubmitApplicationRequest)(nil),   // 8: authors.SubmitApplicationRequest
	(*SubmitApplicationResponse)(nil),  // 9: authors.SubmitApplicationResponse
	(*GetMyApplicationRequest)(nil),    // 10: authors.GetMyApplicationRequest
	(*GetMyApplicationResponse)(nil),   // 11: authors.GetMyApplicationResponse
	(*ListApplicationsRequest)(nil),    // 12: authors.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),   // 13: authors.ListApplicationsResponse
	(*ApproveApplicationRequest)(nil),  // 14: authors.ApproveApplicationRequest
	(*ApproveApplicationResponse)(nil), // 15: authors.ApproveApplicationResponse
	(*RejectApplicationRequest)(nil),   // 16: authors.RejectApplicationRequest
	(*RejectApplicationResponse)(nil),  // 17: authors.RejectApplicationResponse
	(*RevertApplicationRequest)(nil),   // 18: authors.RevertApplicationRequest
	(*RevertApplicationResponse)(nil),  // 19: authors.RevertApplicationResponse
}
var file_authors_proto_depIdxs = []int32{
	0,  // 0: authors.UpsertProfileResponse.author:type_name -> authors.Author
	0,  // 1: authors.GetAuthorResponse.author:type_name -> authors.Author
	0,  // 2: authors.ListAuthorsResponse.authors:type_name -> authors.Author
	7,  // 3: authors.SubmitApplicationResponse.application:type_name -> authors.AuthorApplication
	7,  // 4: authors.GetMyApplicationResponse.application:type_name -> authors.AuthorApplication
	7,  // 5: authors.ListApplicationsResponse.applications:type_name -> authors.AuthorApplication
	7,  // 6: authors.ApproveApplicationResponse.application:type_name -> authors.AuthorApplication
	0,  // 7: authors.ApproveApplicationResponse.author:type_name -> authors.Author
	7,  // 8: authors.RejectApplicationResponse.application:type_name -> authors.AuthorApplication
	7,  // 9: authors.RevertApplicationResponse.application:type_name -> authors.AuthorApplication
	1,  // 10: authors.AuthorsService.UpsertProfile:input_type -> authors.UpsertProfileRequest
	3,  // 11: authors.AuthorsService.GetAuthor:input_type -> authors.GetAuthorRequest
	5,  // 12: authors.AuthorsService.ListAuthors:input_type -> authors.ListAuthorsRequest
	8,  // 13: authors.AuthorsService.SubmitApplication:input_type -> authors.SubmitApplicationRequest
	10, // 14: authors.AuthorsService.GetMyApplication:input_type -> authors.GetMyApplicationRequest
	12, // 15: authors.AuthorsService.ListApplications:input_type -> authors.ListApplicationsRequest
	14, // 16: authors.AuthorsService.ApproveApplication:input_type -> authors.ApproveApplicationRequest
	16, // 17: authors.AuthorsService.RejectApplication:input_type -> authors.RejectApplicationRequest
	18, // 18: authors.AuthorsService.RevertApplication:input_type -> authors.RevertApplicationRequest
	2,  // 19: authors.AuthorsService.UpsertProfile:output_type -> authors.UpsertProfileResponse
	4,  // 20: authors.AuthorsService.GetAuthor:output_type -> authors.GetAuthorResponse
	6,  // 21: authors.AuthorsService.ListAuthors:output_type -> authors.ListAuthorsResponse
	9,  // 22: authors.AuthorsService.SubmitApplication:output_type -> authors.SubmitApplicationResponse
	11, // 23: authors.AuthorsService.GetMyApplication:output_type -> authors.GetMyApplicationResponse
	13, // 24: authors.AuthorsService.ListApplications:output_type -> authors.ListApplicationsResponse
	15, // 25: authors.AuthorsService.ApproveApplication:output_type -> authors.ApproveApplicationResponse
	17, // 26: authors.AuthorsService.RejectApplication:output_type -> authors.RejectApplicationResponse
	19, // 27: authors.AuthorsService.RevertApplication:output_type -> authors.RevertApplicationResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_authors_proto_init() }
func file_authors_proto_init() {
	if File_authors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authors_proto_rawDesc), len(file_authors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authors_proto_goTypes,
		DependencyIndexes: file_authors_proto_depIdxs,
		MessageInfos:      file_authors_proto_msgTypes,
	}.Build()
	File_authors_proto = out.File
	file_authors_proto_goTypes = nil
	file_authors_proto_depIdxs = nil
}
