syntax = "proto3";

package shop;

option go_package = "github.com/Eastwesser/event-horizon/services/shop/proto;shop";

import "validate/validate.proto";

service ShopService {
    rpc GetItems(GetItemsRequest) returns (GetItemsResponse);
    rpc PurchaseItem(PurchaseItemRequest) returns (PurchaseItemResponse);
    rpc GetInventory(GetInventoryRequest) returns (GetInventoryResponse);
}

message Item {
    string id = 1;
    string name = 2;
    string description = 3;
    int32 price = 4;
    string category = 5;
    string game_id = 6;
    string image_url = 7;
    bool available = 8;
    bool owned = 9;
    string purchased_at = 10;
}

message GetItemsRequest {
    string category = 1 [(validate.rules).string = {max_len: 32}];
    string game_id = 2 [(validate.rules).string = {max_len: 32}];
    string user_id = 3 [(validate.rules).string = {max_len: 64}];
}

message GetItemsResponse {
    repeated Item items = 1;
}

message PurchaseItemRequest {
    string user_id = 1 [(validate.rules).string = {min_len: 1, max_len: 64}];
    string item_id = 2 [(validate.rules).string = {min_len: 1, max_len: 64}];
}

message PurchaseItemResponse {
    bool success = 1;
    string message = 2;
    int32 new_balance = 3;
}

message GetInventoryRequest {
    string user_id = 1 [(validate.rules).string = {min_len: 1, max_len: 64}];
}

message GetInventoryResponse {
    repeated Item items = 1;
}
