// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AnalyticsService_RecordEvent_FullMethodName  = "/analytics.AnalyticsService/RecordEvent"
	AnalyticsService_GetDAU_FullMethodName       = "/analytics.AnalyticsService/GetDAU"
	AnalyticsService_GetMAU_FullMethodName       = "/analytics.AnalyticsService/GetMAU"
	AnalyticsService_GetRetention_FullMethodName = "/analytics.AnalyticsService/GetRetention"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error)
	GetDAU(ctx context.Context, in *GetDAURequest, opts ...grpc.CallOption) (*GetDAUResponse, error)
	GetMAU(ctx context.Context, in *GetMAURequest, opts ...grpc.CallOption) (*GetMAUResponse, error)
	GetRetention(ctx context.Context, in *GetRetentionRequest, opts ...grpc.CallOption) (*GetRetentionResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error) {
	out := new(RecordEventResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_RecordEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDAU(ctx context.Context, in *GetDAURequest, opts ...grpc.CallOption) (*GetDAUResponse, error) {
	out := new(GetDAUResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDAU_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMAU(ctx context.Context, in *GetMAURequest, opts ...grpc.CallOption) (*GetMAUResponse, error) {
	out := new(GetMAUResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMAU_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRetention(ctx context.Context, in *GetRetentionRequest, opts ...grpc.CallOption) (*GetRetentionResponse, error) {
	out := new(GetRetentionResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRetention_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility
type AnalyticsServiceServer interface {
	RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error)
	GetDAU(context.Context, *GetDAURequest) (*GetDAUResponse, error)
	GetMAU(context.Context, *GetMAURequest) (*GetMAUResponse, error)
	GetRetention(context.Context, *GetRetentionRequest) (*GetRetentionResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (UnimplementedAnalyticsServiceServer) RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordEvent not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDAU(context.Context, *GetDAURequest) (*GetDAUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDAU not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMAU(context.Context, *GetMAURequest) (*GetMAUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMAU not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRetention(context.Context, *GetRetentionRequest) (*GetRetentionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetention not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_RecordEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).RecordEvent(ctx, req.(*RecordEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDAU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDAURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDAU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDAU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDAU(ctx, req.(*GetDAURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMAU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMAURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMAU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMAU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMAU(ctx, req.(*GetMAURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRetention(ctx, req.(*GetRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordEvent",
			Handler:    _AnalyticsService_RecordEvent_Handler,
		},
		{
			MethodName: "GetDAU",
			Handler:    _AnalyticsService_GetDAU_Handler,
		},
		{
			MethodName: "GetMAU",
			Handler:    _AnalyticsService_GetMAU_Handler,
		},
		{
			MethodName: "GetRetention",
			Handler:    _AnalyticsService_GetRetention_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics.proto",
}
