// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventRequest) Reset() {
	*x = RecordEventRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventRequest) ProtoMessage() {}

func (x *RecordEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventRequest.ProtoReflect.Descriptor instead.
func (*RecordEventRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *RecordEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecordEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type RecordEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventResponse) Reset() {
	*x = RecordEventResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventResponse) ProtoMessage() {}

func (x *RecordEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventResponse.ProtoReflect.Descriptor instead.
func (*RecordEventResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *RecordEventResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetDAURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"` // default 30
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDAURequest) Reset() {
	*x = GetDAURequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDAURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDAURequest) ProtoMessage() {}

func (x *GetDAURequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDAURequest.ProtoReflect.Descriptor instead.
func (*GetDAURequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetDAURequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type DayCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"` // YYYY-MM-DD
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayCount) Reset() {
	*x = DayCount{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayCount) ProtoMessage() {}

func (x *DayCount) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayCount.ProtoReflect.Descriptor instead.
func (*DayCount) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DayCount) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DayCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetDAUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*DayCount            `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDAUResponse) Reset() {
	*x = GetDAUResponse{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDAUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDAUResponse) ProtoMessage() {}

func (x *GetDAUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDAUResponse.ProtoReflect.Descriptor instead.
func (*GetDAUResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetDAUResponse) GetDays() []*DayCount {
	if x != nil {
		return x.Days
	}
	return nil
}

type GetMAURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"` // lookback window, default 30
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMAURequest) Reset() {
	*x = GetMAURequest{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMAURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMAURequest) ProtoMessage() {}

func (x *GetMAURequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMAURequest.ProtoReflect.Descriptor instead.
func (*GetMAURequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetMAURequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetMAUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mau           int64                  `protobuf:"varint,1,opt,name=mau,proto3" json:"mau,omitempty"`
	WindowDays    int32                  `protobuf:"varint,2,opt,name=window_days,json=windowDays,proto3" json:"window_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMAUResponse) Reset() {
	*x = GetMAUResponse{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMAUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMAUResponse) ProtoMessage() {}

func (x *GetMAUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMAUResponse.ProtoReflect.Descriptor instead.
func (*GetMAUResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetMAUResponse) GetMau() int64 {
	if x != nil {
		return x.Mau
	}
	return 0
}

func (x *GetMAUResponse) GetWindowDays() int32 {
	if x != nil {
		return x.WindowDays
	}
	return 0
}

type GetRetentionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CohortDaysAgo int32                  `protobuf:"varint,1,opt,name=cohort_days_ago,json=cohortDaysAgo,proto3" json:"cohort_days_ago,omitempty"` // cohort start day offset, default 7
	WindowDays    int32                  `protobuf:"varint,2,opt,name=window_days,json=windowDays,proto3" json:"window_days,omitempty"`            // return days, default 7
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRetentionRequest) Reset() {
	*x = GetRetentionRequest{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetentionRequest) ProtoMessage() {}

func (x *GetRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetentionRequest.ProtoReflect.Descriptor instead.
func (*GetRetentionRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetRetentionRequest) GetCohortDaysAgo() int32 {
	if x != nil {
		return x.CohortDaysAgo
	}
	return 0
}

func (x *GetRetentionRequest) GetWindowDays() int32 {
	if x != nil {
		return x.WindowDays
	}
	return 0
}

type RetentionPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayN          int32                  `protobuf:"varint,1,opt,name=day_n,json=dayN,proto3" json:"day_n,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionPoint) Reset() {
	*x = RetentionPoint{}
	mi := &file_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPoint) ProtoMessage() {}

func (x *RetentionPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPoint.ProtoReflect.Descriptor instead.
func (*RetentionPoint) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *RetentionPoint) GetDayN() int32 {
	if x != nil {
		return x.DayN
	}
	return 0
}

func (x *RetentionPoint) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type GetRetentionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CohortDay     string                 `protobuf:"bytes,1,opt,name=cohort_day,json=cohortDay,proto3" json:"cohort_day,omitempty"`
	CohortSize    int64                  `protobuf:"varint,2,opt,name=cohort_size,json=cohortSize,proto3" json:"cohort_size,omitempty"`
	Points        []*RetentionPoint      `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRetentionResponse) Reset() {
	*x = GetRetentionResponse{}
	mi := &file_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetentionResponse) ProtoMessage() {}

func (x *GetRetentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetentionResponse.ProtoReflect.Descriptor instead.
func (*GetRetentionResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetRetentionResponse) GetCohortDay() string {
	if x != nil {
		return x.CohortDay
	}
	return ""
}

func (x *GetRetentionResponse) GetCohortSize() int64 {
	if x != nil {
		return x.CohortSize
	}
	return 0
}

func (x *GetRetentionResponse) GetPoints() []*RetentionPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\"o\n" +
	"\x12RecordEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\"%\n" +
	"\x13RecordEventResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"#\n" +
	"\rGetDAURequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"2\n" +
	"\bDayCount\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"9\n" +
	"\x0eGetDAUResponse\x12'\n" +
	"\x04days\x18\x01 \x03(\v2\x13.analytics.DayCountR\x04days\"#\n" +
	"\rGetMAURequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"C\n" +
	"\x0eGetMAUResponse\x12\x10\n" +
	"\x03mau\x18\x01 \x01(\x03R\x03mau\x12\x1f\n" +
	"\vwindow_days\x18\x02 \x01(\x05R\n" +
	"windowDays\"^\n" +
	"\x13GetRetentionRequest\x12&\n" +
	"\x0fcohort_days_ago\x18\x01 \x01(\x05R\rcohortDaysAgo\x12\x1f\n" +
	"\vwindow_days\x18\x02 \x01(\x05R\n" +
	"windowDays\"9\n" +
	"\x0eRetentionPoint\x12\x13\n" +
	"\x05day_n\x18\x01 \x01(\x05R\x04dayN\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\"\x89\x01\n" +
	"\x14GetRetentionResponse\x12\x1d\n" +
	"\n" +
	"cohort_day\x18\x01 \x01(\tR\tcohortDay\x12\x1f\n" +
	"\vcohort_size\x18\x02 \x01(\x03R\n" +
	"cohortSize\x121\n" +
	"\x06points\x18\x03 \x03(\v2\x19.analytics.RetentionPointR\x06points2\xaf\x02\n" +
	"\x10AnalyticsService\x12L\n" +
	"\vRecordEvent\x12\x1d.analytics.RecordEventRequest\x1a\x1e.analytics.RecordEventResponse\x12=\n" +
	"\x06GetDAU\x12\x18.analytics.GetDAURequest\x1a\x19.analytics.GetDAUResponse\x12=\n" +
	"\x06GetMAU\x12\x18.analytics.GetMAURequest\x1a\x19.analytics.GetMAUResponse\x12O\n" +
	"\fGetRetention\x12\x1e.analytics.GetRetentionRequest\x1a\x1f.analytics.GetRetentionResponseBHZFgithub.com/Eastwesser/event-horizon/services/analytics/proto;analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_analytics_proto_goTypes = []any{
	(*RecordEventRequest)(nil),   // 0: analytics.RecordEventRequest
	(*RecordEventResponse)(nil),  // 1: analytics.RecordEventResponse
	(*GetDAURequest)(nil),        // 2: analytics.GetDAURequest
	(*DayCount)(nil),             // 3: analytics.DayCount
	(*GetDAUResponse)(nil),       // 4: analytics.GetDAUResponse
	(*GetMAURequest)(nil),        // 5: analytics.GetMAURequest
	(*GetMAUResponse)(nil),       // 6: analytics.GetMAUResponse
	(*GetRetentionRequest)(nil),  // 7: analytics.GetRetentionRequest
	(*RetentionPoint)(nil),       // 8: analytics.RetentionPoint
	(*GetRetentionResponse)(nil), // 9: analytics.GetRetentionResponse
}
var file_analytics_proto_depIdxs = []int32{
	3, // 0: analytics.GetDAUResponse.days:type_name -> analytics.DayCount
	8, // 1: analytics.GetRetentionResponse.points:type_name -> analytics.RetentionPoint
	0, // 2: analytics.AnalyticsService.RecordEvent:input_type -> analytics.RecordEventRequest
	2, // 3: analytics.AnalyticsService.GetDAU:input_type -> analytics.GetDAURequest
	5, // 4: analytics.AnalyticsService.GetMAU:input_type -> analytics.GetMAURequest
	7, // 5: analytics.AnalyticsService.GetRetention:input_type -> analytics.GetRetentionRequest
	1, // 6: analytics.AnalyticsService.RecordEvent:output_type -> analytics.RecordEventResponse
	4, // 7: analytics.AnalyticsService.GetDAU:output_type -> analytics.GetDAUResponse
	6, // 8: analytics.AnalyticsService.GetMAU:output_type -> analytics.GetMAUResponse
	9, // 9: analytics.AnalyticsService.GetRetention:output_type -> analytics.GetRetentionResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
